### ISSUE TITLE
Non repeteable random numbers using foreach?

### ISSUE THREAD

**Issue by Waldi73** [renozao/doRNG#17]
Hi,
I don't find an obvious explanation to https://stackoverflow.com/q/64145197/13513328
and got exactly the same result as original poster : 122 similar random numbers out of 200 created.
Couldn't figure out why doRNG seems to fail to make two fully equal RN series.
Thanks for your feedback!

**Comment by renozao** [comment]
@Waldi73 see the comment by smovva [in the stackoverflow post](https://stackoverflow.com/questions/64145197/repeatable-random-numbers-using-dorng-package#comment113459755_64145197).

The 2 loops are not equivalent because the call to `sample(x)` leaves the RNG to a different state due to the different size of `x` (11 elements in the first loop vs 9 in the second loop). Hence the `rnorm` calls do not start from the same state and therefore do not return the same random numbers.

Here below is an adapted code that shows that `doRNG` behaves as expected. 

NB: 
* using `set.seed()` has no impact so I removed it
* `Sys.sleep` takes a single number as input. I guess that here it was taking the first element of the result of `sample(x)` without throwing any error. Here I only take the first element.

```R
library(doParallel)
library(doRNG)
library(foreach)

# Make 10 clusters and set them to run in parallel
cl <- makeCluster(10)
registerDoParallel(cl)

## COLLECT THE FIRST SET OF RANDOM NUMBERS 
# Sleep duration for first sample collection
x <- 0:10

# Generate 10 random numbers after a random amount of sleep
rp1 <- foreach(i=1:20, .combine = 'c', .options.RNG=123) %dorng%{ 
  # Sleep for random duration
  Sys.sleep(sample(x)[1L])
  return(rnorm(10,0,1))
}

## SECOND SET RANDOM NUMBERS (different length)
# Sleep duration for second sample collection
x <- 0:8

# Generate 10 random numbers after a random amount of sleep
rp2 <- foreach(i=1:20, .combine = 'c', .options.RNG=123) %dorng%{ 
  # Sleep for random duration
  Sys.sleep(sample(x)[1L])
  return(rnorm(10,0,1))
}

## 3RD SET (same length)
# Sleep duration for second sample collection: same length as for rp1
x <- seq(0, 5, length.out = 11)

# Generate 10 random numbers after a random amount of sleep
rp3 <- foreach(i=1:20, .combine = 'c', .options.RNG=123) %dorng%{ 
  # Sleep for random duration
  Sys.sleep(sample(x)[1L])
  return(rnorm(10,0,1))
}

stopCluster(cl)

identical(rp1, rp2) # FALSE
identical(rp1, rp3) # TRUE

```

**Comment by Waldi73** [comment]
@renozao, thanks for your explaination : this is clear, I didn't remark the length difference in x, doRNG works as expected!
I close the ticket.
